services:
  t4u_pharmacy_web_api:
    image: t4u_pharmacy_web_api:latest
    container_name: t4u_pharmacy_web_api
    restart: always
    environment:
      - TZ=Asia/Taipei
    networks:
      - common_net
    ports:
      - "8080:8080"
      - "8081:8081"
networks:
  common_net: