// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace T4U_Pharmacy_Repository.DBModels;

/// <summary>
/// 客戶
/// </summary>
public partial class Customer
{
    /// <summary>
    /// 序號
    /// </summary>
    public long CustomerId { get; set; }

    /// <summary>
    /// 客戶名稱
    /// </summary>
    public string Name { get; set; }

    /// <summary>
    /// 使用者目前結算餘額
    /// </summary>
    public decimal CashBalance { get; set; }

    /// <summary>
    /// 使用者目前餘額
    /// </summary>
    public decimal CurrentCashBalance { get; set; }

    /// <summary>
    /// 建立日期
    /// </summary>
    public DateTime CreatedDate { get; set; }

    /// <summary>
    /// 修改日期
    /// </summary>
    public DateTime ModifiedDate { get; set; }

    public virtual ICollection<PurchaseHistory> PurchaseHistories { get; set; } = new List<PurchaseHistory>();
}