// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace T4U_Pharmacy_Repository.DBModels;

public partial class KDAN_TESTContext : DbContext
{
    public KDAN_TESTContext(DbContextOptions<KDAN_TESTContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Customer> Customers { get; set; }

    public virtual DbSet<Mask> Masks { get; set; }

    public virtual DbSet<Pharmacy> Pharmacies { get; set; }

    public virtual DbSet<PharmacyMask> PharmacyMasks { get; set; }

    public virtual DbSet<PharmacyMasksStockLog> PharmacyMasksStockLogs { get; set; }

    public virtual DbSet<PharmacyOpeningHour> PharmacyOpeningHours { get; set; }

    public virtual DbSet<PurchaseHistory> PurchaseHistories { get; set; }

    public virtual DbSet<SystemConfig> SystemConfigs { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Customer>(entity =>
        {
            entity.HasKey(e => e.CustomerId).HasName("CUSTOMER_pkey");

            entity.ToTable("CUSTOMER", tb => tb.HasComment("客戶"));

            entity.Property(e => e.CustomerId)
                .HasComment("序號")
                .UseIdentityAlwaysColumn()
                .HasColumnName("CUSTOMER_ID");
            entity.Property(e => e.CashBalance)
                .HasPrecision(10, 2)
                .HasComment("使用者目前結算餘額")
                .HasColumnName("CASH_BALANCE");
            entity.Property(e => e.CreatedDate)
                .HasComment("建立日期")
                .HasColumnType("timestamp without time zone")
                .HasColumnName("CREATED_DATE");
            entity.Property(e => e.CurrentCashBalance)
                .HasPrecision(10, 2)
                .HasComment("使用者目前餘額")
                .HasColumnName("CURRENT_CASH_BALANCE");
            entity.Property(e => e.ModifiedDate)
                .HasComment("修改日期")
                .HasColumnType("timestamp without time zone")
                .HasColumnName("MODIFIED_DATE");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(100)
                .HasComment("客戶名稱")
                .HasColumnName("NAME");
        });

        modelBuilder.Entity<Mask>(entity =>
        {
            entity.HasKey(e => e.MasksId).HasName("MASKS_pkey");

            entity.ToTable("MASKS", tb => tb.HasComment("口罩"));

            entity.Property(e => e.MasksId)
                .HasComment("序號")
                .UseIdentityAlwaysColumn()
                .HasColumnName("MASKS_ID");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(100)
                .HasComment("口罩名稱")
                .HasColumnName("NAME");
        });

        modelBuilder.Entity<Pharmacy>(entity =>
        {
            entity.HasKey(e => e.PharmacyId).HasName("PHARMACY_pkey");

            entity.ToTable("PHARMACY", tb => tb.HasComment("藥局"));

            entity.Property(e => e.PharmacyId)
                .HasComment("序號")
                .UseIdentityAlwaysColumn()
                .HasColumnName("PHARMACY_ID");
            entity.Property(e => e.CashBalance)
                .HasPrecision(10, 2)
                .HasComment("藥局目前結算餘額")
                .HasColumnName("CASH_BALANCE");
            entity.Property(e => e.CreatedDate)
                .HasComment("建立日期")
                .HasColumnType("timestamp without time zone")
                .HasColumnName("CREATED_DATE");
            entity.Property(e => e.CurrentCashBalance)
                .HasPrecision(10, 2)
                .HasComment("藥局目前餘額")
                .HasColumnName("CURRENT_CASH_BALANCE");
            entity.Property(e => e.ModifiedDate)
                .HasComment("修改日期")
                .HasColumnType("timestamp without time zone")
                .HasColumnName("MODIFIED_DATE");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(100)
                .HasComment("藥局名稱")
                .HasColumnName("NAME");
        });

        modelBuilder.Entity<PharmacyMask>(entity =>
        {
            entity.HasKey(e => e.PharmacyMasksId).HasName("PHARMACY_MASKS_pkey");

            entity.ToTable("PHARMACY_MASKS", tb => tb.HasComment("藥局_口罩"));

            entity.Property(e => e.PharmacyMasksId)
                .HasComment("序號")
                .UseIdentityAlwaysColumn()
                .HasColumnName("PHARMACY_MASKS_ID");
            entity.Property(e => e.CreatedDate)
                .HasComment("建立日期")
                .HasColumnType("timestamp without time zone")
                .HasColumnName("CREATED_DATE");
            entity.Property(e => e.MasksId)
                .HasComment("口罩ID(外鍵)MASKS的MASKS_ID")
                .HasColumnName("MASKS_ID");
            entity.Property(e => e.ModifiedDate)
                .HasColumnType("timestamp without time zone")
                .HasColumnName("MODIFIED_DATE");
            entity.Property(e => e.PharmacyId)
                .HasComment("藥局ID(外鍵)PHARMACY的PHARMACY_ID")
                .HasColumnName("PHARMACY_ID");
            entity.Property(e => e.Price)
                .HasPrecision(10, 2)
                .HasComment("單價")
                .HasColumnName("PRICE");

            entity.HasOne(d => d.Masks).WithMany(p => p.PharmacyMasks)
                .HasForeignKey(d => d.MasksId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_MASKS_PHARMACY_MASKS");

            entity.HasOne(d => d.Pharmacy).WithMany(p => p.PharmacyMasks)
                .HasForeignKey(d => d.PharmacyId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PHARMACY_PHARMACY_MASKS");
        });

        modelBuilder.Entity<PharmacyMasksStockLog>(entity =>
        {
            entity.HasKey(e => e.PharmacyMasksStockLogId).HasName("PHARMACY_MASKS_STOCK_LOG_pkey");

            entity.ToTable("PHARMACY_MASKS_STOCK_LOG", tb => tb.HasComment("藥局_口罩_庫存紀錄"));

            entity.Property(e => e.PharmacyMasksStockLogId)
                .HasComment("序號")
                .UseIdentityAlwaysColumn()
                .HasColumnName("PHARMACY_MASKS_STOCK_LOG_ID");
            entity.Property(e => e.CreatedDate)
                .HasComment("建立日期")
                .HasColumnType("timestamp without time zone")
                .HasColumnName("CREATED_DATE");
            entity.Property(e => e.PharmacyMasksId)
                .HasComment("藥局_口罩ID(外鍵)PHARMACY_MASKS的PHARMACY_MASKS_ID")
                .HasColumnName("PHARMACY_MASKS_ID");
            entity.Property(e => e.Price)
                .HasPrecision(10, 2)
                .HasComment("單價(當時進貨或出貨的單價)")
                .HasColumnName("PRICE");
            entity.Property(e => e.StockQuantity)
                .HasComment("口罩數量")
                .HasColumnName("STOCK_QUANTITY");

            entity.HasOne(d => d.PharmacyMasks).WithMany(p => p.PharmacyMasksStockLogs)
                .HasForeignKey(d => d.PharmacyMasksId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PHARMACY_MASKS_PHARMACY_MASKS_STOCK_LOG");
        });

        modelBuilder.Entity<PharmacyOpeningHour>(entity =>
        {
            entity.HasKey(e => e.OpingHoursId).HasName("PHARMACY_OPENING_HOURS_pkey");

            entity.ToTable("PHARMACY_OPENING_HOURS", tb => tb.HasComment("藥局營業時間"));

            entity.Property(e => e.OpingHoursId)
                .HasComment("序號")
                .UseIdentityAlwaysColumn()
                .HasColumnName("OPING_HOURS_ID");
            entity.Property(e => e.CloseTime)
                .HasMaxLength(5)
                .HasComment("關門時間")
                .HasColumnName("CLOSE_TIME");
            entity.Property(e => e.OpenTime)
                .HasMaxLength(5)
                .HasComment("營業時間")
                .HasColumnName("OPEN_TIME");
            entity.Property(e => e.PharmacyId)
                .HasComment("藥局ID(外鍵)PHARMACY的PHARMACY_ID")
                .HasColumnName("PHARMACY_ID");
            entity.Property(e => e.Weekday)
                .HasComment("營業日，星期幾\n0：星期日\n1：星期一\n2：星期二\n3：星期三\n4：星期四\n5：星期五\n6：星期六")
                .HasColumnName("WEEKDAY");

            entity.HasOne(d => d.Pharmacy).WithMany(p => p.PharmacyOpeningHours)
                .HasForeignKey(d => d.PharmacyId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PHARMACY_PHARMACY_OPENING_HOURS");
        });

        modelBuilder.Entity<PurchaseHistory>(entity =>
        {
            entity.HasKey(e => e.PurchaseHistoriesId).HasName("PURCHASE_HISTORIES_pkey");

            entity.ToTable("PURCHASE_HISTORIES", tb => tb.HasComment("客戶購買紀錄"));

            entity.Property(e => e.PurchaseHistoriesId)
                .HasComment("序號")
                .UseIdentityAlwaysColumn()
                .HasColumnName("PURCHASE_HISTORIES_ID");
            entity.Property(e => e.CreatedDate)
                .HasComment("建立日期")
                .HasColumnType("timestamp without time zone")
                .HasColumnName("CREATED_DATE");
            entity.Property(e => e.CustomerId)
                .HasComment("客戶ID(外鍵)CUSTOMER的CUSTOMER_ID")
                .HasColumnName("CUSTOMER_ID");
            entity.Property(e => e.PharmacyMasksId)
                .HasComment("藥局_口罩ID(外鍵)PHARMACY_MASKS的PHARMACY_MASKS_ID")
                .HasColumnName("PHARMACY_MASKS_ID");
            entity.Property(e => e.TransactionAmount)
                .HasPrecision(10, 2)
                .HasComment("交易金額")
                .HasColumnName("TRANSACTION_AMOUNT");
            entity.Property(e => e.TransactionDatetime)
                .HasComment("交易時間")
                .HasColumnType("timestamp without time zone")
                .HasColumnName("TRANSACTION_DATETIME");
            entity.Property(e => e.TransactionQuantity)
                .HasComment("交易數量")
                .HasColumnName("TRANSACTION_QUANTITY");

            entity.HasOne(d => d.Customer).WithMany(p => p.PurchaseHistories)
                .HasForeignKey(d => d.CustomerId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_CUSTOMER_PURCHASE_HISTORIES");

            entity.HasOne(d => d.PharmacyMasks).WithMany(p => p.PurchaseHistories)
                .HasForeignKey(d => d.PharmacyMasksId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PHARMACY_MASKS_PURCHASE_HISTORIES");
        });

        modelBuilder.Entity<SystemConfig>(entity =>
        {
            entity.HasKey(e => e.SystemConfigId).HasName("SYSTEM_CONFIG_pkey");

            entity.ToTable("SYSTEM_CONFIG", tb => tb.HasComment("系統設定"));

            entity.Property(e => e.SystemConfigId)
                .HasComment("序號")
                .UseIdentityAlwaysColumn()
                .HasColumnName("SYSTEM_CONFIG_ID");
            entity.Property(e => e.CreatedDate)
                .HasComment("建立日期")
                .HasColumnType("timestamp without time zone")
                .HasColumnName("CREATED_DATE");
            entity.Property(e => e.Key)
                .IsRequired()
                .HasMaxLength(100)
                .HasComment("系統設定KEY\nUSER_CASH_BALANCE_SETTLEMENT_TIME：使用者餘額結算時間\nPHARMACY_STOCK_SETTLEMENT_TIME：藥局餘額結算時間")
                .HasColumnName("KEY");
            entity.Property(e => e.ModifiedDate)
                .HasComment("修改日期")
                .HasColumnType("timestamp without time zone")
                .HasColumnName("MODIFIED_DATE");
            entity.Property(e => e.Value)
                .IsRequired()
                .HasMaxLength(100)
                .HasComment("系統設定值")
                .HasColumnName("VALUE");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}