// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace T4U_Pharmacy_Repository.DBModels;

/// <summary>
/// 口罩
/// </summary>
public partial class Mask
{
    /// <summary>
    /// 序號
    /// </summary>
    public long MasksId { get; set; }

    /// <summary>
    /// 口罩名稱
    /// </summary>
    public string Name { get; set; }

    public virtual ICollection<PharmacyMask> PharmacyMasks { get; set; } = new List<PharmacyMask>();
}