// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace T4U_Pharmacy_Repository.DBModels;

/// <summary>
/// 藥局
/// </summary>
public partial class Pharmacy
{
    /// <summary>
    /// 序號
    /// </summary>
    public long PharmacyId { get; set; }

    /// <summary>
    /// 藥局名稱
    /// </summary>
    public string Name { get; set; }

    /// <summary>
    /// 藥局目前結算餘額
    /// </summary>
    public decimal CashBalance { get; set; }

    /// <summary>
    /// 藥局目前餘額
    /// </summary>
    public decimal CurrentCashBalance { get; set; }

    /// <summary>
    /// 建立日期
    /// </summary>
    public DateTime CreatedDate { get; set; }

    /// <summary>
    /// 修改日期
    /// </summary>
    public DateTime ModifiedDate { get; set; }

    public virtual ICollection<PharmacyMask> PharmacyMasks { get; set; } = new List<PharmacyMask>();

    public virtual ICollection<PharmacyOpeningHour> PharmacyOpeningHours { get; set; } = new List<PharmacyOpeningHour>();
}