// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace T4U_Pharmacy_Repository.DBModels;

/// <summary>
/// 藥局_口罩
/// </summary>
public partial class PharmacyMask
{
    /// <summary>
    /// 序號
    /// </summary>
    public long PharmacyMasksId { get; set; }

    /// <summary>
    /// 藥局ID(外鍵)PHARMACY的PHARMACY_ID
    /// </summary>
    public long PharmacyId { get; set; }

    /// <summary>
    /// 口罩ID(外鍵)MASKS的MASKS_ID
    /// </summary>
    public long MasksId { get; set; }

    /// <summary>
    /// 單價
    /// </summary>
    public decimal Price { get; set; }

    /// <summary>
    /// 建立日期
    /// </summary>
    public DateTime CreatedDate { get; set; }

    public DateTime ModifiedDate { get; set; }

    public virtual Mask Masks { get; set; }

    public virtual Pharmacy Pharmacy { get; set; }

    public virtual ICollection<PharmacyMasksStockLog> PharmacyMasksStockLogs { get; set; } = new List<PharmacyMasksStockLog>();

    public virtual ICollection<PurchaseHistory> PurchaseHistories { get; set; } = new List<PurchaseHistory>();
}