// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace T4U_Pharmacy_Repository.DBModels;

/// <summary>
/// 藥局營業時間
/// </summary>
public partial class PharmacyOpeningHour
{
    /// <summary>
    /// 序號
    /// </summary>
    public long OpingHoursId { get; set; }

    /// <summary>
    /// 藥局ID(外鍵)PHARMACY的PHARMACY_ID
    /// </summary>
    public long PharmacyId { get; set; }

    /// <summary>
    /// 營業日，星期幾
    /// 0：星期日
    /// 1：星期一
    /// 2：星期二
    /// 3：星期三
    /// 4：星期四
    /// 5：星期五
    /// 6：星期六
    /// </summary>
    public int Weekday { get; set; }

    /// <summary>
    /// 營業時間
    /// </summary>
    public string OpenTime { get; set; }

    /// <summary>
    /// 關門時間
    /// </summary>
    public string CloseTime { get; set; }

    public virtual Pharmacy Pharmacy { get; set; }
}