// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace T4U_Pharmacy_Repository.DBModels;

/// <summary>
/// 藥局_口罩_庫存紀錄
/// </summary>
public partial class PharmacyMasksStockLog
{
    /// <summary>
    /// 序號
    /// </summary>
    public long PharmacyMasksStockLogId { get; set; }

    /// <summary>
    /// 藥局_口罩ID(外鍵)PHARMACY_MASKS的PHARMACY_MASKS_ID
    /// </summary>
    public long PharmacyMasksId { get; set; }

    /// <summary>
    /// 口罩數量
    /// </summary>
    public long StockQuantity { get; set; }

    /// <summary>
    /// 單價(當時進貨或出貨的單價)
    /// </summary>
    public decimal Price { get; set; }

    /// <summary>
    /// 建立日期
    /// </summary>
    public DateTime CreatedDate { get; set; }

    public virtual PharmacyMask PharmacyMasks { get; set; }
}