// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace T4U_Pharmacy_Repository.DBModels;

/// <summary>
/// 客戶購買紀錄
/// </summary>
public partial class PurchaseHistory
{
    /// <summary>
    /// 序號
    /// </summary>
    public long PurchaseHistoriesId { get; set; }

    /// <summary>
    /// 客戶ID(外鍵)CUSTOMER的CUSTOMER_ID
    /// </summary>
    public long CustomerId { get; set; }

    /// <summary>
    /// 藥局_口罩ID(外鍵)PHARMACY_MASKS的PHARMACY_MASKS_ID
    /// </summary>
    public long PharmacyMasksId { get; set; }

    /// <summary>
    /// 交易金額
    /// </summary>
    public decimal TransactionAmount { get; set; }

    /// <summary>
    /// 交易數量
    /// </summary>
    public long TransactionQuantity { get; set; }

    /// <summary>
    /// 交易時間
    /// </summary>
    public DateTime TransactionDatetime { get; set; }

    /// <summary>
    /// 建立日期
    /// </summary>
    public DateTime CreatedDate { get; set; }

    public virtual Customer Customer { get; set; }

    public virtual PharmacyMask PharmacyMasks { get; set; }
}