// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace T4U_Pharmacy_Repository.DBModels;

/// <summary>
/// 系統設定
/// </summary>
public partial class SystemConfig
{
    /// <summary>
    /// 序號
    /// </summary>
    public long SystemConfigId { get; set; }

    /// <summary>
    /// 系統設定KEY
    /// USER_CASH_BALANCE_SETTLEMENT_TIME：使用者餘額結算時間
    /// PHARMACY_STOCK_SETTLEMENT_TIME：藥局餘額結算時間
    /// </summary>
    public string Key { get; set; }

    /// <summary>
    /// 系統設定值
    /// </summary>
    public string Value { get; set; }

    /// <summary>
    /// 建立日期
    /// </summary>
    public DateTime CreatedDate { get; set; }

    /// <summary>
    /// 修改日期
    /// </summary>
    public DateTime ModifiedDate { get; set; }
}