-- Table: public.CUSTOMER

-- DROP TABLE IF EXISTS public."CUSTOMER";

CREATE TABLE IF NOT EXISTS public."CUSTOMER"
(
    "CUSTOMER_ID" bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    "NAME" character varying(100) COLLATE pg_catalog."default" NOT NULL,
    "CASH_BALANCE" numeric(10,2) NOT NULL,
    "CURRENT_CASH_BALANCE" numeric(10,2) NOT NULL,
    "CREATED_DATE" timestamp without time zone NOT NULL,
    "MODIFIED_DATE" timestamp without time zone NOT NULL,
    CONSTRAINT "CUSTOMER_pkey" PRIMARY KEY ("CUSTOMER_ID")
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public."CUSTOMER"
    OWNER to kdan_pharmacy_db;

COMMENT ON TABLE public."CUSTOMER"
    IS '客戶';

COMMENT ON COLUMN public."CUSTOMER"."CUSTOMER_ID"
    IS '序號';

COMMENT ON COLUMN public."CUSTOMER"."NAME"
    IS '客戶名稱';

COMMENT ON COLUMN public."CUSTOMER"."CASH_BALANCE"
    IS '使用者目前結算餘額';

COMMENT ON COLUMN public."CUSTOMER"."CURRENT_CASH_BALANCE"
    IS '使用者目前餘額';

COMMENT ON COLUMN public."CUSTOMER"."CREATED_DATE"
    IS '建立日期';

COMMENT ON COLUMN public."CUSTOMER"."MODIFIED_DATE"
    IS '修改日期';
	
	
-- Table: public.MASKS

-- DROP TABLE IF EXISTS public."MASKS";

CREATE TABLE IF NOT EXISTS public."MASKS"
(
    "MASKS_ID" bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    "NAME" character varying(100) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "MASKS_pkey" PRIMARY KEY ("MASKS_ID")
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public."MASKS"
    OWNER to kdan_pharmacy_db;

COMMENT ON TABLE public."MASKS"
    IS '口罩';

COMMENT ON COLUMN public."MASKS"."MASKS_ID"
    IS '序號';

COMMENT ON COLUMN public."MASKS"."NAME"
    IS '口罩名稱';
	
-- Table: public.PHARMACY

-- DROP TABLE IF EXISTS public."PHARMACY";

CREATE TABLE IF NOT EXISTS public."PHARMACY"
(
    "PHARMACY_ID" bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    "NAME" character varying(100) COLLATE pg_catalog."default" NOT NULL,
    "CASH_BALANCE" numeric(10,2) NOT NULL,
    "CURRENT_CASH_BALANCE" numeric(10,2) NOT NULL,
    "CREATED_DATE" timestamp without time zone NOT NULL,
    "MODIFIED_DATE" timestamp without time zone NOT NULL,
    CONSTRAINT "PHARMACY_pkey" PRIMARY KEY ("PHARMACY_ID")
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public."PHARMACY"
    OWNER to kdan_pharmacy_db;

COMMENT ON TABLE public."PHARMACY"
    IS '藥局';

COMMENT ON COLUMN public."PHARMACY"."PHARMACY_ID"
    IS '序號';

COMMENT ON COLUMN public."PHARMACY"."NAME"
    IS '藥局名稱';

COMMENT ON COLUMN public."PHARMACY"."CASH_BALANCE"
    IS '藥局目前結算餘額';

COMMENT ON COLUMN public."PHARMACY"."CURRENT_CASH_BALANCE"
    IS '藥局目前餘額';

COMMENT ON COLUMN public."PHARMACY"."CREATED_DATE"
    IS '建立日期';

COMMENT ON COLUMN public."PHARMACY"."MODIFIED_DATE"
    IS '修改日期';
	
-- Table: public.PHARMACY_MASKS

-- DROP TABLE IF EXISTS public."PHARMACY_MASKS";

CREATE TABLE IF NOT EXISTS public."PHARMACY_MASKS"
(
    "PHARMACY_MASKS_ID" bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    "PHARMACY_ID" bigint NOT NULL,
    "MASKS_ID" bigint NOT NULL,
    "PRICE" numeric(10,2) NOT NULL,
    "CREATED_DATE" timestamp without time zone NOT NULL,
    "MODIFIED_DATE" timestamp without time zone NOT NULL,
    CONSTRAINT "PHARMACY_MASKS_pkey" PRIMARY KEY ("PHARMACY_MASKS_ID"),
    CONSTRAINT "FK_MASKS_PHARMACY_MASKS" FOREIGN KEY ("MASKS_ID")
        REFERENCES public."MASKS" ("MASKS_ID") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT "FK_PHARMACY_PHARMACY_MASKS" FOREIGN KEY ("PHARMACY_ID")
        REFERENCES public."PHARMACY" ("PHARMACY_ID") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public."PHARMACY_MASKS"
    OWNER to kdan_pharmacy_db;

COMMENT ON TABLE public."PHARMACY_MASKS"
    IS '藥局_口罩';

COMMENT ON COLUMN public."PHARMACY_MASKS"."PHARMACY_MASKS_ID"
    IS '序號';

COMMENT ON COLUMN public."PHARMACY_MASKS"."PHARMACY_ID"
    IS '藥局ID(外鍵)PHARMACY的PHARMACY_ID';

COMMENT ON COLUMN public."PHARMACY_MASKS"."MASKS_ID"
    IS '口罩ID(外鍵)MASKS的MASKS_ID';

COMMENT ON COLUMN public."PHARMACY_MASKS"."PRICE"
    IS '單價';

COMMENT ON COLUMN public."PHARMACY_MASKS"."CREATED_DATE"
    IS '建立日期';

COMMENT ON CONSTRAINT "FK_MASKS_PHARMACY_MASKS" ON public."PHARMACY_MASKS"
    IS '口罩ID(外鍵)MASKS的MASKS_ID';
COMMENT ON CONSTRAINT "FK_PHARMACY_PHARMACY_MASKS" ON public."PHARMACY_MASKS"
    IS '藥局ID(外鍵)PHARMACY的PHARMACY_ID';
	
	
-- Table: public.PHARMACY_MASKS_STOCK_LOG

-- DROP TABLE IF EXISTS public."PHARMACY_MASKS_STOCK_LOG";

CREATE TABLE IF NOT EXISTS public."PHARMACY_MASKS_STOCK_LOG"
(
    "PHARMACY_MASKS_STOCK_LOG_ID" bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    "PHARMACY_MASKS_ID" bigint NOT NULL,
    "STOCK_QUANTITY" bigint NOT NULL,
    "PRICE" numeric(10,2) NOT NULL,
    "CREATED_DATE" timestamp without time zone NOT NULL,
    CONSTRAINT "PHARMACY_MASKS_STOCK_LOG_pkey" PRIMARY KEY ("PHARMACY_MASKS_STOCK_LOG_ID"),
    CONSTRAINT "FK_PHARMACY_MASKS_PHARMACY_MASKS_STOCK_LOG" FOREIGN KEY ("PHARMACY_MASKS_ID")
        REFERENCES public."PHARMACY_MASKS" ("PHARMACY_MASKS_ID") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public."PHARMACY_MASKS_STOCK_LOG"
    OWNER to kdan_pharmacy_db;

COMMENT ON TABLE public."PHARMACY_MASKS_STOCK_LOG"
    IS '藥局_口罩_庫存紀錄';

COMMENT ON COLUMN public."PHARMACY_MASKS_STOCK_LOG"."PHARMACY_MASKS_STOCK_LOG_ID"
    IS '序號';

COMMENT ON COLUMN public."PHARMACY_MASKS_STOCK_LOG"."PHARMACY_MASKS_ID"
    IS '藥局_口罩ID(外鍵)PHARMACY_MASKS的PHARMACY_MASKS_ID';

COMMENT ON COLUMN public."PHARMACY_MASKS_STOCK_LOG"."STOCK_QUANTITY"
    IS '口罩數量';

COMMENT ON COLUMN public."PHARMACY_MASKS_STOCK_LOG"."PRICE"
    IS '單價(當時進貨或出貨的單價)';

COMMENT ON COLUMN public."PHARMACY_MASKS_STOCK_LOG"."CREATED_DATE"
    IS '建立日期';

COMMENT ON CONSTRAINT "FK_PHARMACY_MASKS_PHARMACY_MASKS_STOCK_LOG" ON public."PHARMACY_MASKS_STOCK_LOG"
    IS '藥局_口罩ID(外鍵)PHARMACY_MASKS的PHARMACY_MASKS_ID';
	
	
-- Table: public.PHARMACY_OPENING_HOURS

-- DROP TABLE IF EXISTS public."PHARMACY_OPENING_HOURS";

CREATE TABLE IF NOT EXISTS public."PHARMACY_OPENING_HOURS"
(
    "OPING_HOURS_ID" bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    "PHARMACY_ID" bigint NOT NULL,
    "WEEKDAY" integer NOT NULL,
    "OPEN_TIME" character varying(5) COLLATE pg_catalog."default",
    "CLOSE_TIME" character varying(5) COLLATE pg_catalog."default",
    CONSTRAINT "PHARMACY_OPENING_HOURS_pkey" PRIMARY KEY ("OPING_HOURS_ID"),
    CONSTRAINT "FK_PHARMACY_PHARMACY_OPENING_HOURS" FOREIGN KEY ("PHARMACY_ID")
        REFERENCES public."PHARMACY" ("PHARMACY_ID") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public."PHARMACY_OPENING_HOURS"
    OWNER to kdan_pharmacy_db;

COMMENT ON TABLE public."PHARMACY_OPENING_HOURS"
    IS '藥局營業時間';

COMMENT ON COLUMN public."PHARMACY_OPENING_HOURS"."OPING_HOURS_ID"
    IS '序號';

COMMENT ON COLUMN public."PHARMACY_OPENING_HOURS"."PHARMACY_ID"
    IS '藥局ID(外鍵)PHARMACY的PHARMACY_ID';

COMMENT ON COLUMN public."PHARMACY_OPENING_HOURS"."WEEKDAY"
    IS '營業日，星期幾
0：星期日
1：星期一
2：星期二
3：星期三
4：星期四
5：星期五
6：星期六';

COMMENT ON COLUMN public."PHARMACY_OPENING_HOURS"."OPEN_TIME"
    IS '營業時間';

COMMENT ON COLUMN public."PHARMACY_OPENING_HOURS"."CLOSE_TIME"
    IS '關門時間';
	
	
-- Table: public.PURCHASE_HISTORIES

-- DROP TABLE IF EXISTS public."PURCHASE_HISTORIES";

CREATE TABLE IF NOT EXISTS public."PURCHASE_HISTORIES"
(
    "PURCHASE_HISTORIES_ID" bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    "CUSTOMER_ID" bigint NOT NULL,
    "PHARMACY_MASKS_ID" bigint NOT NULL,
    "TRANSACTION_AMOUNT" numeric(10,2) NOT NULL,
    "TRANSACTION_QUANTITY" bigint NOT NULL,
    "TRANSACTION_DATETIME" timestamp without time zone NOT NULL,
    "CREATED_DATE" timestamp without time zone NOT NULL,
    CONSTRAINT "PURCHASE_HISTORIES_pkey" PRIMARY KEY ("PURCHASE_HISTORIES_ID"),
    CONSTRAINT "FK_CUSTOMER_PURCHASE_HISTORIES" FOREIGN KEY ("CUSTOMER_ID")
        REFERENCES public."CUSTOMER" ("CUSTOMER_ID") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT "FK_PHARMACY_MASKS_PURCHASE_HISTORIES" FOREIGN KEY ("PHARMACY_MASKS_ID")
        REFERENCES public."PHARMACY_MASKS" ("PHARMACY_MASKS_ID") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public."PURCHASE_HISTORIES"
    OWNER to kdan_pharmacy_db;

COMMENT ON TABLE public."PURCHASE_HISTORIES"
    IS '客戶購買紀錄';

COMMENT ON COLUMN public."PURCHASE_HISTORIES"."PURCHASE_HISTORIES_ID"
    IS '序號';

COMMENT ON COLUMN public."PURCHASE_HISTORIES"."CUSTOMER_ID"
    IS '客戶ID(外鍵)CUSTOMER的CUSTOMER_ID';

COMMENT ON COLUMN public."PURCHASE_HISTORIES"."PHARMACY_MASKS_ID"
    IS '藥局_口罩ID(外鍵)PHARMACY_MASKS的PHARMACY_MASKS_ID';

COMMENT ON COLUMN public."PURCHASE_HISTORIES"."TRANSACTION_AMOUNT"
    IS '交易金額';

COMMENT ON COLUMN public."PURCHASE_HISTORIES"."TRANSACTION_QUANTITY"
    IS '交易數量';

COMMENT ON COLUMN public."PURCHASE_HISTORIES"."TRANSACTION_DATETIME"
    IS '交易時間';

COMMENT ON COLUMN public."PURCHASE_HISTORIES"."CREATED_DATE"
    IS '建立日期';
	
	
-- Table: public.SYSTEM_CONFIG

-- DROP TABLE IF EXISTS public."SYSTEM_CONFIG";

CREATE TABLE IF NOT EXISTS public."SYSTEM_CONFIG"
(
    "SYSTEM_CONFIG_ID" bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    "KEY" character varying(100) COLLATE pg_catalog."default" NOT NULL,
    "VALUE" character varying(100) COLLATE pg_catalog."default" NOT NULL,
    "CREATED_DATE" timestamp without time zone NOT NULL,
    "MODIFIED_DATE" timestamp without time zone NOT NULL,
    CONSTRAINT "SYSTEM_CONFIG_pkey" PRIMARY KEY ("SYSTEM_CONFIG_ID")
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public."SYSTEM_CONFIG"
    OWNER to kdan_pharmacy_db;

COMMENT ON TABLE public."SYSTEM_CONFIG"
    IS '系統設定';

COMMENT ON COLUMN public."SYSTEM_CONFIG"."SYSTEM_CONFIG_ID"
    IS '序號';

COMMENT ON COLUMN public."SYSTEM_CONFIG"."KEY"
    IS '系統設定KEY
USER_CASH_BALANCE_SETTLEMENT_TIME：使用者餘額結算時間
PHARMACY_STOCK_SETTLEMENT_TIME：藥局餘額結算時間';

COMMENT ON COLUMN public."SYSTEM_CONFIG"."VALUE"
    IS '系統設定值';

COMMENT ON COLUMN public."SYSTEM_CONFIG"."CREATED_DATE"
    IS '建立日期';

COMMENT ON COLUMN public."SYSTEM_CONFIG"."MODIFIED_DATE"
    IS '修改日期';